-- 1. 用户表 (存储学员信息)
create table if not exists public.users (
  id uuid default gen_random_uuid() primary key,
  phone text unique not null,
  name text not null,
  token text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 每日任务表 (存储日期对应的题目)
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  date date unique not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 打卡记录表 (存储学员打卡内容)
create table if not exists public.checkins (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) not null,
  user_name text, -- 冗余字段方便查询，可选
  user_phone text, -- 冗余字段方便查询，可选
  date date not null,
  answer text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date)
);

-- 4. 开启行级安全策略 (RLS) - 简单起见，初期可以先允许所有读写，或者设置简单策略
alter table public.users enable row level security;
alter table public.questions enable row level security;
alter table public.checkins enable row level security;

-- 开放读写权限 (注意：这是为了演示方便，生产环境建议配置更严格的 Policy)
create policy "Enable read access for all users" on public.users for select using (true);
create policy "Enable read access for all users" on public.questions for select using (true);
create policy "Enable read/write access for all users" on public.checkins for all using (true);

